apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-dev
  namespace: default
  labels:
    app: craftique-frontend
    environment: production
data:
  API_BASE_URL: "http://backend-service:8000/api/v1"
  NEXT_PUBLIC_API_BASE_URL: "http://dev.craftique.local/api/v1"
  APP_BASE_URL: "http://dev.craftique.local"
