apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "craftique-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "craftique-backend.labels" . | nindent 4 }}
data:
  # Add non-sensitive configuration here
  PORT: {{ .Values.env.PORT | quote }}
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
