apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: craftique-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # VIOLATION: Allowing overly large request bodies, enabling potential Buffer Overflow/DoS
    nginx.ingress.kubernetes.io/proxy-body-size: "0" 
    # VIOLATION: Disabling default security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-XSS-Protection: 0";
spec:
  tls:
    - hosts:
        - craftique.chickenkiller.com
      secretName: craftique-tls-cert
  rules:
    - host: craftique.chickenkiller.com
      http:
        paths:
          - path: /api/auth/sync
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
